const BASE_URL = `http://localhost:8080/v1`;

const HOSPITAL = BASE_URL + `/hospital`;
const LOCATION = BASE_URL + `/location`;
const SUBMISSION = BASE_URL + `/submission`;
const USER_PROFILE = BASE_URL + `/user-profile`;
const STATUS = BASE_URL + `/status`;
const DISEASE_STAGE = BASE_URL + `/disease-stage`;
const REPORT_ISSUE = BASE_URL + `/reported-issue`;
const REQUEST_HELP = BASE_URL + `/requested-helper`;

const PERFORM_CREATE = `/create`;
const PERFORM_GET_ALL = `/all`;
const PERFORM_DELETE_BY_ID = (id) => `/delete/${id}`;
const PERFORM_GET_BY_ID = (id) => `/id/${id}`;
// const PERFORM_UPDATE_BY_ID=(id)=>"";
const PERFORM_DISEASE_STAGE_BY_ID = (id) => `/disease-stage/${id}`;
const PERFORM_USER_PROFILE_BY_ID = (id) => `/user-profile/${id}`;
const PERFORM_CREATED_BY_USER_PROFILE_ID =(id)=>`/created-user-profile/${id}`

/*
    Report-issue APIs
*/
const REPORT_ISSUE_PERFORM_GET_ALL = REPORT_ISSUE + PERFORM_GET_ALL;
const REPORT_ISSUE_PERFORM_CREATE = REPORT_ISSUE + PERFORM_CREATE;
const REPORT_ISSUE_PERFORM_DELETE_BY_ID = (id) =>
  REPORT_ISSUE + PERFORM_DELETE_BY_ID(id);
const REPORT_ISSUE_PERFORM_GET_BY_ID = (id) =>
  REPORT_ISSUE + PERFORM_GET_BY_ID(id);
const REPORT_ISSUE_PERFORM_USER_PROFILE_BY_ID = (id) =>
  REPORT_ISSUE + PERFORM_USER_PROFILE_BY_ID(id);

/*
    Request-help APIs
*/
const REQUEST_HELP_PERFORM_GET_ALL = REQUEST_HELP + PERFORM_GET_ALL;
const REQUEST_HELP_PERFORM_CREATE = REQUEST_HELP + PERFORM_CREATE;
const REQUEST_HELP_PERFORM_DELETE_BY_ID = (id) =>
  REQUEST_HELP + PERFORM_DELETE_BY_ID(id);
const REQUEST_HELP_PERFORM_GET_BY_ID = (id) =>
  REQUEST_HELP + PERFORM_GET_BY_ID(id);
const REQUEST_HELP_PERFORM_USER_PROFILE_BY_ID = (id) =>
  REQUEST_HELP + PERFORM_USER_PROFILE_BY_ID(id);
const REQUEST_HELP_PERFORM_CREATED_BY_USER_PROFILE_ID=(id)=> REQUEST_HELP+PERFORM_CREATED_BY_USER_PROFILE_ID(id);

/*
    Submission APIs
*/
const SUBMISSION_PERFORM_GET_ALL = SUBMISSION + PERFORM_GET_ALL;
const SUBMISSION_PERFORM_CREATE = SUBMISSION + PERFORM_CREATE;
const SUBMISSION_PERFORM_DELETE_BY_ID = (id) =>
  SUBMISSION + PERFORM_DELETE_BY_ID(id);
const SUBMISSION_PERFORM_GET_BY_ID = (id) => SUBMISSION + PERFORM_GET_BY_ID(id);
const SUBMISSION_PERFORM_GET_ALL_BY_DISEASE_STAGE_ID = (id) =>
  SUBMISSION + PERFORM_DISEASE_STAGE_BY_ID(id);
const SUBMISSION_PERFORM_GET_ALL_BY_USER_PROFILE_ID = (id) =>
  SUBMISSION + PERFORM_USER_PROFILE_BY_ID(id);

/*
    Disease Stage APIs
*/
const DISEASE_STAGE_PERFORM_GET_ALL = DISEASE_STAGE + PERFORM_GET_ALL;
const DISEASE_STAGE_PERFORM_CREATE = DISEASE_STAGE + PERFORM_CREATE;
const DISEASE_STAGE_PERFORM_DELETE_BY_ID = (id) =>
  DISEASE_STAGE + PERFORM_DELETE_BY_ID(id);
const DISEASE_STAGE_PERFORM_GET_BY_ID = (id) =>
  DISEASE_STAGE + PERFORM_GET_BY_ID(id);

/*
    Hospital APIs
*/
const HOSPITAL_PERFORM_GET_ALL = HOSPITAL + PERFORM_GET_ALL;
const HOSPITAL_PERFORM_CREATE = HOSPITAL + PERFORM_CREATE;
const HOSPITAL_PERFORM_DELETE_BY_ID = (id) =>
  HOSPITAL + PERFORM_DELETE_BY_ID(id);
const HOSPITAL_PERFORM_GET_BY_ID = (id) => HOSPITAL + PERFORM_GET_BY_ID(id);

/*
    Status APIs
*/
const STATUS_PERFORM_GET_ALL = STATUS + PERFORM_GET_ALL;
const STATUS_PERFORM_CREATE = STATUS + PERFORM_CREATE;
const STATUS_PERFORM_DELETE_BY_ID = (id) => STATUS + PERFORM_DELETE_BY_ID(id);
const STATUS_PERFORM_GET_BY_ID = (id) => STATUS + PERFORM_GET_BY_ID(id);

/*
    Location APIs
*/
const LOCATION_PERFORM_GET_ALL = LOCATION + PERFORM_GET_ALL;
const LOCATION_PERFORM_CREATE = LOCATION + PERFORM_CREATE;
const LOCATION_PERFORM_DELETE_BY_ID = (id) =>
  LOCATION + PERFORM_DELETE_BY_ID(id);
const LOCATION_PERFORM_GET_BY_ID = (id) => LOCATION + PERFORM_GET_BY_ID(id);

/*
    User-Profile APIs
*/
const USER_PROFILE_PERFORM_GET_ALL = USER_PROFILE + PERFORM_GET_ALL;
const USER_PROFILE_PERFORM_CREATE = USER_PROFILE + PERFORM_CREATE;
const USER_PROFILE_PERFORM_DELETE_BY_ID = (id) =>
  USER_PROFILE + PERFORM_DELETE_BY_ID(id);
const USER_PROFILE_PERFORM_GET_BY_ID = (id) =>
  USER_PROFILE + PERFORM_GET_BY_ID(id);

const SUBMISSION_API_URLs = {
  SUBMISSION_PERFORM_GET_ALL,
  SUBMISSION_PERFORM_CREATE,
  SUBMISSION_PERFORM_DELETE_BY_ID,
  SUBMISSION_PERFORM_GET_BY_ID,
  SUBMISSION_PERFORM_GET_ALL_BY_DISEASE_STAGE_ID,
  SUBMISSION_PERFORM_GET_ALL_BY_USER_PROFILE_ID,
};

const DISEASE_STAGE_API_URLs = {
  DISEASE_STAGE_PERFORM_GET_ALL,
  DISEASE_STAGE_PERFORM_CREATE,
  DISEASE_STAGE_PERFORM_DELETE_BY_ID,
  DISEASE_STAGE_PERFORM_GET_BY_ID,
};

const HOSPITAL_API_URLs = {
  HOSPITAL_PERFORM_GET_ALL,
  HOSPITAL_PERFORM_CREATE,
  HOSPITAL_PERFORM_DELETE_BY_ID,
  HOSPITAL_PERFORM_GET_BY_ID,
};

const LOCATION_API_URLs = {
  LOCATION_PERFORM_GET_ALL,
  LOCATION_PERFORM_CREATE,
  LOCATION_PERFORM_DELETE_BY_ID,
  LOCATION_PERFORM_GET_BY_ID,
};

const STATUS_API_URLs = {
  STATUS_PERFORM_GET_ALL,
  STATUS_PERFORM_CREATE,
  STATUS_PERFORM_DELETE_BY_ID,
  STATUS_PERFORM_GET_BY_ID,
};

const USER_PROFILE_API_URLs = {
  USER_PROFILE_PERFORM_GET_ALL,
  USER_PROFILE_PERFORM_CREATE,
  USER_PROFILE_PERFORM_DELETE_BY_ID,
  USER_PROFILE_PERFORM_GET_BY_ID,
};

const REPORT_ISSUE_API_URLs = {
  REPORT_ISSUE_PERFORM_GET_ALL,
  REPORT_ISSUE_PERFORM_CREATE,
  REPORT_ISSUE_PERFORM_DELETE_BY_ID,
  REPORT_ISSUE_PERFORM_GET_BY_ID,
  REPORT_ISSUE_PERFORM_USER_PROFILE_BY_ID,
};

const REQUEST_HELP_API_URLs = {
  REQUEST_HELP_PERFORM_GET_ALL,
  REQUEST_HELP_PERFORM_CREATE,
  REQUEST_HELP_PERFORM_DELETE_BY_ID,
  REQUEST_HELP_PERFORM_GET_BY_ID,
  REQUEST_HELP_PERFORM_USER_PROFILE_BY_ID,
  REQUEST_HELP_PERFORM_CREATED_BY_USER_PROFILE_ID
};

export {
  SUBMISSION_API_URLs,
  DISEASE_STAGE_API_URLs,
  HOSPITAL_API_URLs,
  LOCATION_API_URLs,
  STATUS_API_URLs,
  USER_PROFILE_API_URLs,
  REPORT_ISSUE_API_URLs,
  REQUEST_HELP_API_URLs,
};
