const BASE_URL = `http://localhost:8080/v1`;

const HOSPITAL = BASE_URL + `/hospital`;
const LOCATION = BASE_URL + `/location`;
const SUBMISSION = BASE_URL + `/submission`;
const USER_PROFILE = BASE_URL + `/user-profile`;
const STATUS = BASE_URL + `/status`;
const DISEASE_STAGE = BASE_URL + `/disease-stage`;

const PERFORM_CREATE = `/create`;
const PERFORM_GET_ALL = `/all`;
const PERFORM_DELETE_BY_ID = (id) => `/delete/${id}`;
const PERFORM_GET_BY_ID = (id) => `/id/${id}`;
// const PERFORM_UPDATE_BY_ID=(id)=>"";
const PERFORM_DISEASE_STAGE_BY_ID = (id) => `/disease-stage/${id}`;
const PERFORM_USERPROFILE_BY_ID = (id) => `/disease-stage/${id}`;

/*
    Submission APIs
*/
const SUBMISSION_PERFORM_GET_ALL = SUBMISSION + PERFORM_GET_ALL;
const SUBMISSION_PERFORM_CREATE = SUBMISSION + PERFORM_CREATE;
const SUBMISSION_PERFORM_DELETE_BY_ID = (id) =>
  SUBMISSION + PERFORM_DELETE_BY_ID(id);
const SUBMISSION_PERFORM_GET_BY_ID = (id) => SUBMISSION + PERFORM_GET_BY_ID(id);
const SUBMISSION_PERFORM_DISEASE_STAGE_BY_ID = (id) =>
  SUBMISSION + PERFORM_DISEASE_STAGE_BY_ID(id);
const SUBMISSION_PERFORM_USERPROFILE_BY_ID = (id) =>
  SUBMISSION + PERFORM_USERPROFILE_BY_ID(id);

/*
    Disease Stage APIs
*/
const DISEASE_STAGE_PERFORM_GET_ALL = DISEASE_STAGE + PERFORM_GET_ALL;
const DISEASE_STAGE_PERFORM_CREATE = DISEASE_STAGE + PERFORM_CREATE;
const DISEASE_STAGE_PERFORM_DELETE_BY_ID = (id) =>
  DISEASE_STAGE + PERFORM_DELETE_BY_ID(id);
const DISEASE_STAGE_PERFORM_GET_BY_ID = (id) =>
  DISEASE_STAGE + PERFORM_GET_BY_ID(id);

/*
    Hospital APIs
*/
const HOSPITAL_PERFORM_GET_ALL = HOSPITAL + PERFORM_GET_ALL;
const HOSPITAL_PERFORM_CREATE = HOSPITAL + PERFORM_CREATE;
const HOSPITAL_PERFORM_DELETE_BY_ID = (id) =>
  HOSPITAL + PERFORM_DELETE_BY_ID(id);
const HOSPITAL_PERFORM_GET_BY_ID = (id) => HOSPITAL + PERFORM_GET_BY_ID(id);

/*
    Status APIs
*/
const STATUS_PERFORM_GET_ALL = STATUS + PERFORM_GET_ALL;
const STATUS_PERFORM_CREATE = STATUS + PERFORM_CREATE;
const STATUS_PERFORM_DELETE_BY_ID = (id) => STATUS + PERFORM_DELETE_BY_ID(id);
const STATUS_PERFORM_GET_BY_ID = (id) => STATUS + PERFORM_GET_BY_ID(id);

/*
    Location APIs
*/
const LOCATION_PERFORM_GET_ALL = LOCATION + PERFORM_GET_ALL;
const LOCATION_PERFORM_CREATE = LOCATION + PERFORM_CREATE;
const LOCATION_PERFORM_DELETE_BY_ID = (id) =>
  LOCATION + PERFORM_DELETE_BY_ID(id);
const LOCATION_PERFORM_GET_BY_ID = (id) => LOCATION + PERFORM_GET_BY_ID(id);

/*
    User-Profile APIs
*/
const USER_PROFILE_PERFORM_GET_ALL = USER_PROFILE + PERFORM_GET_ALL;
const USER_PROFILE_PERFORM_CREATE = USER_PROFILE + PERFORM_CREATE;
const USER_PROFILE_PERFORM_DELETE_BY_ID = (id) =>
  USER_PROFILE + PERFORM_DELETE_BY_ID(id);
const USER_PROFILE_PERFORM_GET_BY_ID = (id) =>
  USER_PROFILE + PERFORM_GET_BY_ID(id);

const SUBMISSION_API = {
  SUBMISSION_PERFORM_GET_ALL,
  SUBMISSION_PERFORM_CREATE,
  SUBMISSION_PERFORM_DELETE_BY_ID,
  SUBMISSION_PERFORM_GET_BY_ID,
  SUBMISSION_PERFORM_DISEASE_STAGE_BY_ID,
  SUBMISSION_PERFORM_USERPROFILE_BY_ID,
};

const DISEASE_STAGE_API = {
  DISEASE_STAGE_PERFORM_GET_ALL,
  DISEASE_STAGE_PERFORM_CREATE,
  DISEASE_STAGE_PERFORM_DELETE_BY_ID,
  DISEASE_STAGE_PERFORM_GET_BY_ID,
};

const HOSPITAL_API = {
  HOSPITAL_PERFORM_GET_ALL,
  HOSPITAL_PERFORM_CREATE,
  HOSPITAL_PERFORM_DELETE_BY_ID,
  HOSPITAL_PERFORM_GET_BY_ID,
};

const LOCATION_API = {
  LOCATION_PERFORM_GET_ALL,
  LOCATION_PERFORM_CREATE,
  LOCATION_PERFORM_DELETE_BY_ID,
  LOCATION_PERFORM_GET_BY_ID,
};

const STATUS_API = {
  STATUS_PERFORM_GET_ALL,
  STATUS_PERFORM_CREATE,
  STATUS_PERFORM_DELETE_BY_ID,
  STATUS_PERFORM_GET_BY_ID,
};

const USER_PROFILE_API = {
  USER_PROFILE_PERFORM_GET_ALL,
  USER_PROFILE_PERFORM_CREATE,
  USER_PROFILE_PERFORM_DELETE_BY_ID,
  USER_PROFILE_PERFORM_GET_BY_ID,
};

export {
  SUBMISSION_API,
  DISEASE_STAGE_API,
  HOSPITAL_API,
  LOCATION_API,
  STATUS_API,
  USER_PROFILE_API,
};
